services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: ghcr.io/olivier-2018/softwareengg-app:latest
    container_name: softwareengg-app
    restart: always
    env_file: .env
    # Expose port to host only in local Dev
    #ports:
    #  - "5003:5003"
    volumes:
      - ./sqlite_db:/app/sqlite_db
    networks: [ "contado_net" ]

  # Uncomment for Continuous Deployment from GitHub Container Registry
  # See .github workflow
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks: [ "contado_net" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

networks:
   contado_net:
      name: contado_net
      driver: bridge
      external: true
