services:
  app:
    image: softwareengg-app:latest
    build: .
    container_name: softwareengg-app
    env_file: .env
    # Expose port to host only in local Dev
    # ports:
      # - "5003:5003"
    volumes:
      - sqlite_db:/app
      - upload_space:/app/static/client/wav
    restart: unless-stopped

volumes:
  sqlite_db:
  upload_space:
